---
output: html_document
editor_options: 
  chunk_output_type: console
---

# Plotting built-up index

## Load libraries

Refer to the `ipython` script that runs on _Colab_ for NDVI and NDBI extraction.

```{r}
# libraries for spatial
library(raster)
library(sf)

# general
library(data.table)

# libraries for plotting
library(ggplot2)
library(patchwork)
```

```{r}
# load rasters
ndbi <- raster("data/raster/duke_transects_ndbi.tif")
ndvi <- raster("data/raster/duke_transects_ndvi.tif")

# load transects and buffer
# find files
transects <- list.files("data/raw/", pattern = "gpx", full.names = TRUE)
# read files as sf
transects <- lapply(transects, sf::st_read, layer = "tracks")

# get buffer sizes in metres
buffer <- rep(c(40, 90), each = length(transects))

# convert to UTM17, buffer by 40 or 90m and reconvert
transect_buffers <- mapply(function(z, b) {
  z <- st_transform(z, 32617)
  z <- st_buffer(z, b)
  z <- st_transform(z, 4326)
  z$buffer_size <- b
  return(z)
}, append(transects, transects), buffer, SIMPLIFY = F)

# reduce
tb <- Reduce(rbind, transect_buffers)
tb <- tb[, c("name", "buffer_size")]
tb$label <- sprintf('(%s)', rep(letters[1:6], 2))

# save transects
st_write(tb, "data/spatial/transect_buffers_dual.gpkg")
```

## Plot transect buffer and environment rasters

### Built-up index

```{r}
bu_map <-
  tm_shape(built_up)+
  tm_raster(style = "cont", midpoint = -0.5,
            palette = viridis::inferno(20), legend.show = F)+
  tm_shape(tb)+
  tm_borders(col = "white", lty = rep(c(1, 2), each = 6))+
  tm_shape(tb[1:6, ])+
  tm_text(text = "label", col = "white", fontface = "bold", 
          xmod = -1, ymod = 1)+
  tm_scale_bar(breaks = c(0, 0.5, 1.0),
               text.size = 1,
               text.color = "white")

bu_map
tmap::tmap_save(bu_map, filename = "figures/fig_built_up.png", width = 185/25)
```

### NDVI

```{r}
ndvi_map <-
  tm_shape(ndvi)+
  tm_raster(style = "cont", midpoint = 0.5,
            palette = viridis::viridis(20, direction = -1), 
            legend.show = F)+
  tm_shape(tb)+
  tm_borders(col = "black", lty = rep(c(1, 2), each = 6))+
  tm_shape(tb[1:6, ])+
  tm_text(text = "label", col = "black", fontface = "bold", 
          xmod = -1, ymod = 1)+
  tm_scale_bar(breaks = c(0, 0.5, 1.0),
               text.size = 1,
               text.color = "black")

tmap::tmap_save(ndvi_map, filename = "figures/fig_ndvi.png", width = 185/25)
```

## Boxplots of environmental values

### NDBI

```{r}
# mask by transect buffer of 90m
ndbi <- raster::mask(ndbi, as(tb[tb$buffer_size == 90, ], "Spatial"))

# rescale values within buffer zone only
values(ndbi) <- scales::rescale(values(ndbi))

# extract values for each transect and each buffer size
ndbi_vals <- lapply(transect_buffers, function(z) {
  vals_here <- extract(ndbi, as(z, "Spatial"))
  data.table(transect_name = z$name,
             label = z$label,
             buffer_size = z$buffer_size,
             ndbi = unlist(vals_here))
})

# join by name
ndbi_vals <- rbindlist(ndbi_vals)
ndbi_vals <- split(ndbi_vals, ndbi_vals$transect_name)
```

```{r}
plots <- lapply(ndbi_vals, function(df) {
  ggplot()+
  geom_jitter(data = df,
              aes(
                x = factor(buffer_size),
                y = ndbi,
                col = ndbi),
              # col = "steelblue",
              width = 0.3,
              alpha = 0.1,
              size = 0.2,
              show.legend = F
  )+
  geom_boxplot(data = df,
              aes(
                x = factor(buffer_size),
                y = ndbi),
              fill = "grey90",
              colour = "black",
              alpha = 0.5,
              outlier.size = 0,
              width = 0.2,
              lwd = 0.2)+
  scale_colour_gradientn(
    colours = rev(pals::kovesi.linear_kryw_5_100_c64(9))
  )+
  coord_flip(ylim = c(0, 1), xlim = c(0.9, 2.1))+
  theme_test()+
  theme(axis.text.y = element_text(angle = 90, hjust = 0.5),
        axis.title.y = element_text(size = 8))+
  labs(y = "NDBI",
       x = "Buffer size (m)")
})

# arrange plots together
fig_boxplot_bu <- 
wrap_plots(plots, nrow = 2) +
  patchwork::plot_annotation(tag_levels = "a",
                             tag_prefix = "(",
                             tag_suffix = ")") &
  theme(plot.tag = element_text(face = "bold"))

fig_boxplot_bu

# save
ggsave(fig_boxplot_bu, filename = "figures/fig_boxplot_bu.png", 
       width = 185/25, height = 70/25)
```

### NDVI

```{r}
# mask by transect buffer of 90m
ndvi <- raster::mask(ndvi, as(tb[tb$buffer_size == 90, ], "Spatial"))

# rescale values within buffer zone only
values(ndvi) <- scales::rescale(values(ndvi))

# extract values for each transect and each buffer size
ndvi_vals <- lapply(transect_buffers, function(z) {
  vals_here <- extract(ndvi, as(z, "Spatial"))
  data.table(transect_name = z$name,
             label = z$label,
             buffer_size = z$buffer_size,
             ndvi = unlist(vals_here))
})

# join by name
ndvi_vals <- rbindlist(ndvi_vals)
ndvi_vals <- split(ndvi_vals, ndvi_vals$transect_name)
```

```{r}
plots <-
  lapply(ndvi_vals, function(df) {
  ggplot()+
  geom_jitter(data = df,
              aes(
                x = factor(buffer_size),
                y = ndvi,
                col = ndvi),
              width = 0.3,
              alpha = 0.1,
              size = 0.2,
              show.legend = F
  )+
  geom_boxplot(data = df,
              aes(
                x = factor(buffer_size),
                y = ndvi),
              fill = "grey90",
              colour = "black",
              alpha = 0.5,
              outlier.size = 0,
              width = 0.2,
              lwd = 0.2)+
  scale_colour_viridis_c(direction = -1)+
  coord_flip(ylim = c(0, 1), xlim = c(0.9, 2.1))+
  theme_test()+
  theme(axis.text.y = element_text(angle = 90, hjust = 0.5),
        axis.title.y = element_text(size = 8))+
  labs(y = "NDVI",
       x = "Buffer size (m)")
})

# arrange plots together
fig_boxplot_ndvi <- wrap_plots(plots, nrow = 2) +
  patchwork::plot_annotation(tag_levels = "a",
                             tag_prefix = "(",
                             tag_suffix = ")") &
  theme(plot.tag = element_text(face = "bold"))

fig_boxplot_ndvi

# save
ggsave(fig_boxplot_ndvi, filename = "figures/fig_boxplot_ndvi.png", 
       width = 185/25, height = 70/25)
```

## Combine map and boxplots

### Built-up index

```{r}
library(magick)

# read both images and stack
fig_box <- image_read("figures/fig_boxplot_bu.png")
fig_map <- image_read("figures/fig_built_up.png")
fig_combined <- image_append(c(fig_map, fig_box), stack = T)

# save combined image
image_write(image = fig_combined, path = "figures/fig_map_boxplot.png")
```

### NDVI

```{r}
library(magick)

# read both images and stack
fig_box <- image_read("figures/fig_boxplot_ndvi.png")
fig_map <- image_read("figures/fig_ndvi.png")
fig_combined <- image_append(c(fig_map, fig_box), stack = T)

# save combined image
image_write(image = fig_combined, path = "figures/fig_ndvi_map_boxplot.png")
```

## Transect wise metric mean and variance

```{r}
# convert to data frames
env_data <- lapply(list(ndbi_vals, ndvi_vals), rbindlist)

# assign key
env_data <- lapply(env_data, function(df) {
  df[, key := seq(nrow(df))]
})

# bind sideways
env_data <- Reduce(merge, env_data)

# plot ndvi ~ ndbi
fig_ndvi_ndbi <- ggplot()+
  geom_point(data = env_data,
             aes(ndvi, ndbi,
                 colour = transect_name),
             size = 0.1, alpha = 0.1,
             show.legend = F)+
  geom_smooth(data = env_data,
              aes(ndvi, ndbi,
                  group = transect_name),
              method = "glm",
              size = 0.2)+
  facet_grid( ~ buffer_size,
              labeller = label_both)+
  coord_equal()+
  theme_test()+
  theme(legend.position = "top")+
  labs(x = "NDVI", y = "Built-up index")

# save
ggsave(fig_ndvi_ndbi, filename = "figures/fig_ndvi_ndbi.png", width = 185/25)

# get mean and variance
env_data_summary <- dcast(env_data, transect_name + buffer_size ~ 1, 
      fun.aggregate = list(mean, var), value.var = c("ndvi", "ndbi"))

# save data
fwrite(env_data_summary, file = "data/data_transect_ndbi_ndvi.csv")
```

